/* SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2026 Hamish Johnson
 * Quantum Information Systems Lab, SFU Physics
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * ============================================================================
 * MoVI Pro attribute/field table -- ported from build/re-notes/hamfly_attr_table.h
 * (itself generated by tools/gen_attr_table.py from hardware-validated evidence:
 *   qx_param_map.csv   (field layout, validated against GCU firmware 2.3.5)
 *   hw_write_scan.csv  (read -> write -> read-back -> restore, on the real gimbal)
 *
 * writable = 1 ONLY where the write was proven on hardware (63 fields).
 * Everything else is read-only telemetry. Do not flip a writable flag
 * without a hardware verification run.
 *
 * DECODE MODEL
 *   physical = raw / scale, where raw is a BIG-ENDIAN integer at
 *   [offset : offset+size], interpreted signed when is_signed = 1.
 *   Write: raw = round(physical * scale).
 *
 * WRITING (critical): most of these attributes are multi-field QB/QX
 *   structs. Writing one field REQUIRES a read-modify-write of the whole
 *   struct (read, patch [offset:offset+size], set the QB payload's type
 *   byte to 0x01, write back the SAME observed length). A naive
 *   single-field write ZEROES the sibling fields. See hamfly_settings_rmw.h.
 *
 * Wire form: attr <= 255 is QB (16-bit big-endian length, DATA = attr byte
 *   + payload); attr > 255 is QX (single length byte, <= 127, varint
 *   attribute + addressing fields in the body).
 *
 * Port notes (v2, this file):
 *  - Data unchanged from the re-notes source -- every row copied verbatim.
 *  - Storage changed from `static const` (one private copy per translation
 *    unit) to `extern const` here + a single definition in
 *    hamfly_attr_table.c, so the ~4 KB table exists exactly once in the
 *    image regardless of how many modules include this header.
 *  - Attr 110 is deliberately ABSENT (as in the source table): its 2020
 *    firmware layout (49-byte struct, "Aux Port Function" at offset 32) is
 *    stale against firmware 2.3.5, which returns a 1-byte reply. A decoder
 *    must never report a field value for it -- omitting the row makes that
 *    the natural behaviour of hamfly_settings_find_field() (returns NULL)
 *    rather than something every caller has to remember to special-case.
 *
 * NOT build-verified -- no C compiler was available when this was written.
 */

#ifndef HAMFLY_ATTR_TABLE_H
#define HAMFLY_ATTR_TABLE_H

#include <stdint.h>

#define HAMFLY_ATTR_IS_QX(a)  ((a) > 255u)

typedef struct {
    uint16_t    attr;       /* attribute id                                    */
    uint8_t     offset;     /* byte offset of the field within the payload     */
    uint8_t     size;       /* 1, 2 or 4 bytes                                 */
    uint8_t     is_signed;  /* 1 = signed big-endian                           */
    uint8_t     writable;   /* 1 = verified WRITE_OK on hardware               */
    uint8_t     has_range;  /* 1 = vmin/vmax are meaningful                    */
    float       scale;      /* physical = raw / scale                          */
    float       vmin, vmax; /* declared range (clamp writes to this)           */
    const char *name;
    const char *units;
} hamfly_attr_field_t;

#define HAMFLY_ATTR_FIELD_COUNT 180u

/* Single definition lives in hamfly_attr_table.c. */
extern const hamfly_attr_field_t hamfly_attr_fields[HAMFLY_ATTR_FIELD_COUNT];

#endif /* HAMFLY_ATTR_TABLE_H */
